// Package adapters wires AllMyAgents' single, agent-agnostic Effective
// Developer Context (see internal/context) into each supported AI coding
// agent, using that agent's own documented mechanism for local/project
// context. Every adapter renders the exact same context text — none of
// them recompute or duplicate Developer Profile / Session Override logic.
package adapters

import "fmt"

// Status is the outcome of one adapter's Configure call.
type Status string

const (
	// StatusConfigured means the adapter's integration is set up (or was
	// already set up) and is safe to consider working.
	StatusConfigured Status = "configured"
	// StatusSkipped means the adapter intentionally did nothing, for a
	// non-fatal reason explained in Result.Detail — most commonly because
	// the file it would manage already exists and is tracked by git, so
	// AllMyAgents refuses to touch it rather than risk mixing personal
	// context into shared project instructions.
	StatusSkipped Status = "skipped"
	// StatusError means the adapter actually failed to do its job.
	StatusError Status = "error"
)

// Result reports what one adapter did for one agent.
type Result struct {
	Agent  string
	Status Status
	Detail string
}

// Adapter configures one AI agent's integration with the Effective
// Developer Context for a project.
type Adapter interface {
	// Name is the stable, lowercase identifier for the agent, e.g.
	// "claude-code".
	Name() string
	// Configure sets up the agent's integration in projectDir. rendered is
	// the current Effective Developer Context (see context.Render); it is
	// empty when no Developer Profile exists yet, which adapters that need
	// static content should treat as a non-fatal skip.
	Configure(projectDir string, rendered string) Result
}

// All returns every AllMyAgents agent adapter, in a fixed, stable order.
func All() []Adapter {
	return []Adapter{
		ClaudeCode{},
		Codex{},
		Copilot{},
		Gemini{},
		Antigravity{},
	}
}

// RunAll configures every adapter independently. One adapter panicking or
// returning an error never prevents the others from running: each adapter
// gets its own isolated call, and a panic is converted into a StatusError
// result rather than propagating.
func RunAll(projectDir string, rendered string) []Result {
	adapters := All()
	results := make([]Result, 0, len(adapters))
	for _, a := range adapters {
		results = append(results, safeConfigure(a, projectDir, rendered))
	}
	return results
}

func safeConfigure(a Adapter, projectDir, rendered string) (result Result) {
	defer func() {
		if r := recover(); r != nil {
			result = Result{Agent: a.Name(), Status: StatusError, Detail: fmt.Sprintf("panic: %v", r)}
		}
	}()
	return a.Configure(projectDir, rendered)
}

// generatedMarker opens every personal, local-only context file AllMyAgents
// generates for an agent, so anyone who opens it (or sees it as an
// untracked file in `git status`) immediately knows what it is, that it's
// personal rather than a project's real shared instructions, and that it
// shouldn't be committed or hand-edited.
const generatedMarker = "<!-- Generated by AllMyAgents — personal, local-only developer context.\n" +
	"     Do not edit by hand or commit; regenerate via `allmyagents init-project`. -->"

// buildContent prepends the generatedMarker to rendered context text.
func buildContent(rendered string) string {
	return generatedMarker + "\n\n" + rendered
}

// noProfileYetDetail is the Skipped reason used by every adapter that needs
// static rendered content but none is available yet.
const noProfileYetDetail = "no Developer Profile yet — run `allmyagents init`, then re-run `allmyagents init-project`"

// gitExcludedNote and noGitRepositoryNote are the two honest, mutually
// exclusive descriptions of whether a generated file actually ended up
// protected by .git/info/exclude. Adapters must use whichever one actually
// happened — never assume exclusion succeeded just because writing the
// file did.
const (
	gitExcludedNote     = "git-excluded, local only"
	noGitRepositoryNote = "no git repository found here yet — this file is not automatically protected if you run `git init`/`git add` later; add it to .gitignore yourself if you plan to"
)
