package adapters

import (
	"path/filepath"
	"strings"
	"testing"
)

func TestAntigravityConfigureWritesRuleFile(t *testing.T) {
	projectDir := newGitRepo(t)

	result := Antigravity{}.Configure(projectDir, "- Learning method: Socratic\n")
	if result.Status != StatusConfigured {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusConfigured, result.Detail)
	}

	content := readFile(t, filepath.Join(projectDir, ".agents", "rules", "allmyagents-context.md"))
	if !strings.HasPrefix(content, "---\ntrigger: always_on\n---\n\n") {
		t.Fatalf("expected Always On rule frontmatter, got %q", content)
	}
	if !strings.Contains(content, "Generated by AllMyAgents") {
		t.Fatalf("expected generated marker, got %q", content)
	}

	exclude := readFile(t, filepath.Join(projectDir, ".git", "info", "exclude"))
	if !strings.Contains(exclude, ".agents/rules/allmyagents-context.md") {
		t.Fatalf("expected rule file in git exclude, got %q", exclude)
	}
}

func TestAntigravityConfigureSkipsTrackedRuleFile(t *testing.T) {
	projectDir := newGitRepoWithTrackedFile(t, ".agents/rules/allmyagents-context.md", "---\ntrigger: manual\n---\n\nteam rule\n")

	result := Antigravity{}.Configure(projectDir, "- Learning method: Socratic\n")
	if result.Status != StatusSkipped {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusSkipped, result.Detail)
	}
}

func TestAntigravityConfigureSkipsWithoutDeveloperProfile(t *testing.T) {
	projectDir := newGitRepo(t)

	result := Antigravity{}.Configure(projectDir, "")
	if result.Status != StatusSkipped {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusSkipped, result.Detail)
	}
}
