package adapters

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCodexConfigureWritesAgentsFile(t *testing.T) {
	projectDir := newGitRepo(t)

	result := Codex{}.Configure(projectDir, "- Learning method: Socratic\n")
	if result.Status != StatusConfigured {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusConfigured, result.Detail)
	}

	content := readFile(t, filepath.Join(projectDir, "AGENTS.md"))
	if !strings.Contains(content, "Generated by AllMyAgents") {
		t.Fatalf("expected generated marker in AGENTS.md, got %q", content)
	}
	if !strings.Contains(content, "Learning method: Socratic") {
		t.Fatalf("expected rendered context in AGENTS.md, got %q", content)
	}

	exclude := readFile(t, filepath.Join(projectDir, ".git", "info", "exclude"))
	if !strings.Contains(exclude, "AGENTS.md") {
		t.Fatalf("expected AGENTS.md in git exclude, got %q", exclude)
	}
}

func TestCodexConfigureIsIdempotent(t *testing.T) {
	projectDir := newGitRepo(t)

	if result := (Codex{}.Configure(projectDir, "- A: B\n")); result.Status != StatusConfigured {
		t.Fatalf("first Configure: Status = %q, detail: %s", result.Status, result.Detail)
	}
	first := readFile(t, filepath.Join(projectDir, "AGENTS.md"))

	if result := (Codex{}.Configure(projectDir, "- A: B\n")); result.Status != StatusConfigured {
		t.Fatalf("second Configure: Status = %q, detail: %s", result.Status, result.Detail)
	}
	second := readFile(t, filepath.Join(projectDir, "AGENTS.md"))

	if first != second {
		t.Fatalf("AGENTS.md changed on idempotent call:\nfirst:  %s\nsecond: %s", first, second)
	}
	exclude := readFile(t, filepath.Join(projectDir, ".git", "info", "exclude"))
	if strings.Count(exclude, "AGENTS.md") != 1 {
		t.Fatalf("expected exactly one AGENTS.md exclude entry, got %q", exclude)
	}
}

func TestCodexConfigureSkipsTrackedAgentsFile(t *testing.T) {
	projectDir := newGitRepoWithTrackedFile(t, "AGENTS.md", "# Team instructions\n\nRun `make test` before committing.\n")

	result := Codex{}.Configure(projectDir, "- Learning method: Socratic\n")
	if result.Status != StatusSkipped {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusSkipped, result.Detail)
	}

	content := readFile(t, filepath.Join(projectDir, "AGENTS.md"))
	if content != "# Team instructions\n\nRun `make test` before committing.\n" {
		t.Fatalf("tracked AGENTS.md must not be modified, got %q", content)
	}
}

func TestCodexConfigureSkipsWithoutDeveloperProfile(t *testing.T) {
	projectDir := newGitRepo(t)

	result := Codex{}.Configure(projectDir, "")
	if result.Status != StatusSkipped {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusSkipped, result.Detail)
	}
	if _, err := os.Stat(filepath.Join(projectDir, "AGENTS.md")); err == nil {
		t.Fatal("expected no AGENTS.md to be written without a Developer Profile")
	}
}

func TestCodexConfigureWorksOutsideGitRepo(t *testing.T) {
	projectDir := t.TempDir()

	result := Codex{}.Configure(projectDir, "- A: B\n")
	if result.Status != StatusConfigured {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusConfigured, result.Detail)
	}
	if _, err := os.Stat(filepath.Join(projectDir, "AGENTS.md")); err != nil {
		t.Fatalf("expected AGENTS.md to be created outside a git repo: %v", err)
	}
}

// TestCodexConfigureOutsideGitRepoDoesNotClaimGitExclusion proves Finding
// C: outside a git repository nothing was actually excluded, so the
// success message must not claim it was.
func TestCodexConfigureOutsideGitRepoDoesNotClaimGitExclusion(t *testing.T) {
	projectDir := t.TempDir()

	result := Codex{}.Configure(projectDir, "- A: B\n")
	if result.Status != StatusConfigured {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusConfigured, result.Detail)
	}
	if strings.Contains(result.Detail, "git-excluded") {
		t.Fatalf("must not claim git exclusion outside a git repository, got detail %q", result.Detail)
	}
	if !strings.Contains(result.Detail, "no git repository") {
		t.Fatalf("expected an honest 'no git repository' note, got detail %q", result.Detail)
	}
}

// TestCodexConfigureInsideGitRepoClaimsGitExclusion is the positive
// counterpart: inside a real repository, exclusion did happen and the
// message should say so.
func TestCodexConfigureInsideGitRepoClaimsGitExclusion(t *testing.T) {
	projectDir := newGitRepo(t)

	result := Codex{}.Configure(projectDir, "- A: B\n")
	if result.Status != StatusConfigured {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusConfigured, result.Detail)
	}
	if !strings.Contains(result.Detail, "git-excluded, local only") {
		t.Fatalf("expected the detail to confirm git exclusion inside a real repo, got %q", result.Detail)
	}
}

// TestCodexConfigureSkipsExistingUntrackedForeignFile proves Finding B at
// the adapter level (not just the shared writeManagedFile helper): a
// pre-existing, untracked, non-AllMyAgents AGENTS.md must survive
// byte-for-byte and Codex must report skipped.
func TestCodexConfigureSkipsExistingUntrackedForeignFile(t *testing.T) {
	projectDir := newGitRepo(t)
	foreignContent := "# My own untracked notes\n\nNot generated by AllMyAgents.\n"
	if err := os.WriteFile(filepath.Join(projectDir, "AGENTS.md"), []byte(foreignContent), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	result := Codex{}.Configure(projectDir, "- Learning method: Socratic\n")
	if result.Status != StatusSkipped {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusSkipped, result.Detail)
	}

	got := readFile(t, filepath.Join(projectDir, "AGENTS.md"))
	if got != foreignContent {
		t.Fatalf("foreign untracked AGENTS.md was modified:\ngot:  %q\nwant: %q", got, foreignContent)
	}
}
