package adapters

import (
	"path/filepath"
	"strings"
	"testing"
)

func TestCopilotConfigureWritesInstructionsFile(t *testing.T) {
	projectDir := newGitRepo(t)

	result := Copilot{}.Configure(projectDir, "- Learning method: Socratic\n")
	if result.Status != StatusConfigured {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusConfigured, result.Detail)
	}

	content := readFile(t, filepath.Join(projectDir, ".github", "copilot-instructions.md"))
	if !strings.Contains(content, "Generated by AllMyAgents") {
		t.Fatalf("expected generated marker, got %q", content)
	}

	exclude := readFile(t, filepath.Join(projectDir, ".git", "info", "exclude"))
	if !strings.Contains(exclude, ".github/copilot-instructions.md") {
		t.Fatalf("expected copilot-instructions.md in git exclude, got %q", exclude)
	}
}

func TestCopilotConfigureSkipsTrackedInstructionsFile(t *testing.T) {
	projectDir := newGitRepoWithTrackedFile(t, ".github/copilot-instructions.md", "# Team coding standards\n")

	result := Copilot{}.Configure(projectDir, "- Learning method: Socratic\n")
	if result.Status != StatusSkipped {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusSkipped, result.Detail)
	}

	content := readFile(t, filepath.Join(projectDir, ".github", "copilot-instructions.md"))
	if content != "# Team coding standards\n" {
		t.Fatalf("tracked copilot-instructions.md must not be modified, got %q", content)
	}
}

func TestCopilotConfigureSkipsWithoutDeveloperProfile(t *testing.T) {
	projectDir := newGitRepo(t)

	result := Copilot{}.Configure(projectDir, "")
	if result.Status != StatusSkipped {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusSkipped, result.Detail)
	}
}
