package adapters

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGeminiConfigureWritesContentFileAndSettings(t *testing.T) {
	projectDir := newGitRepo(t)

	result := Gemini{}.Configure(projectDir, "- Learning method: Socratic\n")
	if result.Status != StatusConfigured {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusConfigured, result.Detail)
	}

	content := readFile(t, filepath.Join(projectDir, "GEMINI.local.md"))
	if !strings.Contains(content, "Generated by AllMyAgents") {
		t.Fatalf("expected generated marker, got %q", content)
	}
	if !strings.Contains(content, "Learning method: Socratic") {
		t.Fatalf("expected rendered context, got %q", content)
	}

	settings := decodeSettings(t, filepath.Join(projectDir, ".gemini", "settings.json"))
	names := fileNamesFromSettings(t, settings)
	if !containsString(names, "GEMINI.local.md") {
		t.Fatalf("expected context.fileName to include GEMINI.local.md, got %v", names)
	}
	if !containsString(names, "GEMINI.md") {
		t.Fatalf("expected context.fileName to still include the default GEMINI.md, got %v", names)
	}

	exclude := readFile(t, filepath.Join(projectDir, ".git", "info", "exclude"))
	if !strings.Contains(exclude, "GEMINI.local.md") || !strings.Contains(exclude, ".gemini/settings.json") {
		t.Fatalf("expected both managed paths in git exclude, got %q", exclude)
	}
}

func TestGeminiConfigurePreservesExistingContextFileNames(t *testing.T) {
	projectDir := newGitRepo(t)
	settingsPath := filepath.Join(projectDir, ".gemini", "settings.json")
	writeJSONObjectForTest(t, settingsPath, map[string]any{
		"context": map[string]any{"fileName": []any{"CONTEXT.md"}},
		"other":   "keep-me",
	})

	result := Gemini{}.Configure(projectDir, "- A: B\n")
	if result.Status != StatusConfigured {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusConfigured, result.Detail)
	}

	settings := decodeSettings(t, settingsPath)
	if settings["other"] != "keep-me" {
		t.Fatalf("expected unrelated settings key to be preserved, got %#v", settings)
	}
	names := fileNamesFromSettings(t, settings)
	if !containsString(names, "CONTEXT.md") || !containsString(names, "GEMINI.local.md") {
		t.Fatalf("expected both the existing and new filenames, got %v", names)
	}
}

func TestGeminiConfigureIsIdempotent(t *testing.T) {
	projectDir := newGitRepo(t)

	if result := (Gemini{}.Configure(projectDir, "- A: B\n")); result.Status != StatusConfigured {
		t.Fatalf("first Configure: Status = %q, detail: %s", result.Status, result.Detail)
	}
	settingsPath := filepath.Join(projectDir, ".gemini", "settings.json")
	firstSettings := readFile(t, settingsPath)

	if result := (Gemini{}.Configure(projectDir, "- A: B\n")); result.Status != StatusConfigured {
		t.Fatalf("second Configure: Status = %q, detail: %s", result.Status, result.Detail)
	}
	secondSettings := readFile(t, settingsPath)

	if firstSettings != secondSettings {
		t.Fatalf("settings.json changed on idempotent call:\nfirst:  %s\nsecond: %s", firstSettings, secondSettings)
	}
}

func TestGeminiConfigureSkipsTrackedSettings(t *testing.T) {
	projectDir := newGitRepoWithTrackedFile(t, ".gemini/settings.json", `{"context": {"fileName": "GEMINI.md"}}`)

	result := Gemini{}.Configure(projectDir, "- A: B\n")
	if result.Status != StatusSkipped {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusSkipped, result.Detail)
	}
}

func TestGeminiConfigureSkipsTrackedContentFile(t *testing.T) {
	projectDir := newGitRepoWithTrackedFile(t, "GEMINI.local.md", "team content\n")

	result := Gemini{}.Configure(projectDir, "- A: B\n")
	if result.Status != StatusSkipped {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusSkipped, result.Detail)
	}
}

// TestGeminiConfigureOutsideGitRepoDoesNotClaimGitExclusion proves Finding
// C: outside a git repository nothing was actually excluded, so the
// success message must not claim it was.
func TestGeminiConfigureOutsideGitRepoDoesNotClaimGitExclusion(t *testing.T) {
	projectDir := t.TempDir()

	result := Gemini{}.Configure(projectDir, "- A: B\n")
	if result.Status != StatusConfigured {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusConfigured, result.Detail)
	}
	if strings.Contains(result.Detail, "git-excluded") {
		t.Fatalf("must not claim git exclusion outside a git repository, got detail %q", result.Detail)
	}
	if !strings.Contains(result.Detail, "no git repository") {
		t.Fatalf("expected an honest 'no git repository' note, got detail %q", result.Detail)
	}
}

// TestGeminiConfigureSkipsExistingUntrackedForeignContentFile proves
// Finding B for Gemini's content file specifically: a pre-existing,
// untracked, non-AllMyAgents GEMINI.local.md must survive byte-for-byte.
func TestGeminiConfigureSkipsExistingUntrackedForeignContentFile(t *testing.T) {
	projectDir := newGitRepo(t)
	foreignContent := "personal Gemini notes, not from AllMyAgents\n"
	if err := os.WriteFile(filepath.Join(projectDir, "GEMINI.local.md"), []byte(foreignContent), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	result := Gemini{}.Configure(projectDir, "- A: B\n")
	if result.Status != StatusSkipped {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusSkipped, result.Detail)
	}

	got := readFile(t, filepath.Join(projectDir, "GEMINI.local.md"))
	if got != foreignContent {
		t.Fatalf("foreign untracked GEMINI.local.md was modified:\ngot:  %q\nwant: %q", got, foreignContent)
	}
}

func TestGeminiConfigureSkipsWithoutDeveloperProfile(t *testing.T) {
	projectDir := newGitRepo(t)

	result := Gemini{}.Configure(projectDir, "")
	if result.Status != StatusSkipped {
		t.Fatalf("Status = %q, want %q (detail: %s)", result.Status, StatusSkipped, result.Detail)
	}
}

func fileNamesFromSettings(t *testing.T, settings map[string]any) []string {
	t.Helper()
	contextField, ok := settings["context"].(map[string]any)
	if !ok {
		t.Fatalf("expected 'context' object in settings, got %#v", settings)
	}
	raw, ok := contextField["fileName"].([]any)
	if !ok {
		t.Fatalf("expected 'context.fileName' array, got %#v", contextField["fileName"])
	}
	names := make([]string, 0, len(raw))
	for _, v := range raw {
		names = append(names, v.(string))
	}
	return names
}

func containsString(ss []string, want string) bool {
	for _, s := range ss {
		if s == want {
			return true
		}
	}
	return false
}

func writeJSONObjectForTest(t *testing.T, path string, settings map[string]any) {
	t.Helper()
	if err := writeJSONObject(path, settings); err != nil {
		t.Fatalf("writeJSONObject returned error: %v", err)
	}
}
