package adapters

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestWriteManagedFileSkipsExistingUntrackedForeignFile proves Finding B:
// an untracked file AllMyAgents did not generate itself must never be
// overwritten, even though it isn't tracked by git.
func TestWriteManagedFileSkipsExistingUntrackedForeignFile(t *testing.T) {
	projectDir := newGitRepo(t)
	fullPath := filepath.Join(projectDir, "AGENTS.md")
	foreignContent := "# My own notes\n\nThis was not generated by AllMyAgents.\n"
	if err := os.WriteFile(fullPath, []byte(foreignContent), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}

	skipReason, note, err := writeManagedFile(projectDir, "AGENTS.md", buildContent("- A: B\n"))
	if err != nil {
		t.Fatalf("writeManagedFile returned error: %v", err)
	}
	if skipReason == "" {
		t.Fatal("expected a skip reason for a pre-existing foreign file")
	}
	if note != "" {
		t.Fatalf("expected no protection note when skipping, got %q", note)
	}

	got := readFile(t, fullPath)
	if got != foreignContent {
		t.Fatalf("foreign file was modified:\ngot:  %q\nwant: %q", got, foreignContent)
	}
}

// TestWriteManagedFileRegeneratesItsOwnPreviousOutput proves that an
// existing file carrying AllMyAgents' own marker is still safe to refresh
// (idempotent regeneration), even outside a plain empty-directory start.
func TestWriteManagedFileRegeneratesItsOwnPreviousOutput(t *testing.T) {
	projectDir := newGitRepo(t)

	if _, _, err := writeManagedFile(projectDir, "AGENTS.md", buildContent("- A: B\n")); err != nil {
		t.Fatalf("first writeManagedFile returned error: %v", err)
	}

	skipReason, note, err := writeManagedFile(projectDir, "AGENTS.md", buildContent("- A: C\n"))
	if err != nil {
		t.Fatalf("second writeManagedFile returned error: %v", err)
	}
	if skipReason != "" {
		t.Fatalf("expected regeneration of AllMyAgents' own file to succeed, got skip: %s", skipReason)
	}
	if note != gitExcludedNote {
		t.Fatalf("note = %q, want %q", note, gitExcludedNote)
	}

	got := readFile(t, filepath.Join(projectDir, "AGENTS.md"))
	if !strings.Contains(got, "- A: C") {
		t.Fatalf("expected regenerated content, got %q", got)
	}
}

// TestWriteManagedFileSkipsSymlink proves the small, focused symlink
// protection: AllMyAgents must never write through a symlink it did not
// create, since that could silently modify a file outside the project
// entirely.
func TestWriteManagedFileSkipsSymlink(t *testing.T) {
	projectDir := newGitRepo(t)
	outsideDir := t.TempDir()
	outsideFile := filepath.Join(outsideDir, "outside.md")
	outsideContent := "content that lives outside the project\n"
	if err := os.WriteFile(outsideFile, []byte(outsideContent), 0o644); err != nil {
		t.Fatalf("WriteFile returned error: %v", err)
	}
	linkPath := filepath.Join(projectDir, "AGENTS.md")
	if err := os.Symlink(outsideFile, linkPath); err != nil {
		t.Fatalf("Symlink returned error: %v", err)
	}

	skipReason, note, err := writeManagedFile(projectDir, "AGENTS.md", buildContent("- A: B\n"))
	if err != nil {
		t.Fatalf("writeManagedFile returned error: %v", err)
	}
	if skipReason == "" {
		t.Fatal("expected a skip reason for a symlinked path")
	}
	if note != "" {
		t.Fatalf("expected no protection note when skipping, got %q", note)
	}

	got := readFile(t, outsideFile)
	if got != outsideContent {
		t.Fatalf("symlink target was modified:\ngot:  %q\nwant: %q", got, outsideContent)
	}
}

// TestWriteManagedFileCreatesWhenAbsent is the plain "file doesn't exist
// yet" path, unaffected by the Finding B changes.
func TestWriteManagedFileCreatesWhenAbsent(t *testing.T) {
	projectDir := newGitRepo(t)

	skipReason, note, err := writeManagedFile(projectDir, "AGENTS.md", buildContent("- A: B\n"))
	if err != nil {
		t.Fatalf("writeManagedFile returned error: %v", err)
	}
	if skipReason != "" {
		t.Fatalf("expected no skip for a new file, got %q", skipReason)
	}
	if note != gitExcludedNote {
		t.Fatalf("note = %q, want %q", note, gitExcludedNote)
	}
}
