package adapters

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/n7ptd2xr8c-cell/allmyagents/internal/profile"
)

// writeManagedFile writes content to <projectDir>/<relPath>, but only when
// doing so cannot destroy something that isn't AllMyAgents' own output:
//
//  1. relPath already tracked by git            -> skip, untouched
//  2. relPath exists as a symlink                -> skip, untouched
//  3. relPath exists, doesn't carry generatedMarker -> skip, untouched
//  4. relPath exists and carries generatedMarker  -> safe to regenerate
//  5. relPath doesn't exist                       -> create it
//
// On success it reports, via protectionNote, whether the file actually
// ended up protected by .git/info/exclude (gitExcludedNote) or not
// (noGitRepositoryNote) — callers must use this rather than assuming
// exclusion always succeeded.
//
// A non-empty skipReason with a nil error is the normal, non-fatal
// "don't touch this file" path, not a failure.
func writeManagedFile(projectDir, relPath, content string) (skipReason string, protectionNote string, err error) {
	if profile.IsTracked(projectDir, relPath) {
		return fmt.Sprintf(
			"%s already exists and is tracked by git — AllMyAgents does not modify a project's shared instructions; personal context was not written",
			relPath,
		), "", nil
	}

	fullPath := filepath.Join(projectDir, relPath)

	info, statErr := os.Lstat(fullPath)
	switch {
	case statErr == nil && info.Mode()&os.ModeSymlink != 0:
		return fmt.Sprintf(
			"%s already exists as a symlink — AllMyAgents does not write through a symlink it did not create",
			relPath,
		), "", nil
	case statErr == nil:
		existing, readErr := os.ReadFile(fullPath)
		if readErr != nil {
			return "", "", fmt.Errorf("read existing %s: %w", relPath, readErr)
		}
		if !strings.Contains(string(existing), generatedMarker) {
			return fmt.Sprintf(
				"%s already exists and wasn't generated by AllMyAgents — not overwriting it",
				relPath,
			), "", nil
		}
	case !os.IsNotExist(statErr):
		return "", "", fmt.Errorf("check existing %s: %w", relPath, statErr)
	}

	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		return "", "", fmt.Errorf("create directory for %s: %w", relPath, err)
	}
	if err := os.WriteFile(fullPath, []byte(content), 0o644); err != nil {
		return "", "", fmt.Errorf("write %s: %w", relPath, err)
	}

	if !profile.HasGitRepository(projectDir) {
		return "", noGitRepositoryNote, nil
	}
	if err := profile.EnsureGitExcluded(projectDir, relPath); err != nil {
		return "", "", fmt.Errorf("wrote %s but could not git-exclude it: %w", relPath, err)
	}
	return "", gitExcludedNote, nil
}
